#!/usr/bin/env node
/**
 * Regenerate the Handyman index.md (Obsidian MOC) from live workspace state.
 *
 * Faithful port of `scripts/index_md.py`. The Map Of Content hub lists what
 * actually exists in HARNESS_WORKSPACE -- the feature backlog grouped by
 * status, the docs, the progress files, and the backlog reports -- so it stays
 * accurate without hand-editing. A `## Notes` section is preserved across
 * regenerations for operator-authored content.
 *
 * Only files that exist are linked, always as relative markdown links. The
 * file is OKF-conformant (index.md is a reserved file in the Open Knowledge
 * Format: directory listing, no frontmatter), and Obsidian renders markdown
 * links the same as wikilinks, so the vault loses nothing.
 *
 * Usage:
 *   node dist/index_md.js [--root PATH]
 *
 * Exit codes: 0 ok, 1 error.
 */
import { readdirSync, readFileSync, realpathSync, statSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { resolveDocsDir, resolveWorkspace } from "./core/index.js";

const DOCS = ["business", "architecture", "conventions", "verification"] as const;
const STATUS_ORDER = ["in_progress", "pending", "blocked"] as const;
export const NOTES_HEADING = "## Notes";

function err(msg: string): number {
  process.stderr.write(`error: ${msg}\n`);
  return 1;
}

function isFile(path: string): boolean {
  try {
    return statSync(path).isFile();
  } catch {
    return false;
  }
}

/** `.md` entries in `dir`, sorted by filename (mirrors `sorted(dir.glob("*.md"))`). */
function mdNamesSorted(dir: string): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  return entries.filter((name) => name.endsWith(".md")).sort();
}

/** Filename without the trailing `.md` (mirrors Python `Path.stem` for `*.md`). */
function stemOf(name: string): string {
  return name.slice(0, -3);
}

/** Python `obj.get(key, dflt)` -- present-key wins even for falsy values. */
function pyGet(obj: Record<string, unknown>, key: string, dflt: unknown): unknown {
  return Object.hasOwn(obj, key) ? obj[key] : dflt;
}

function projectName(workspace: string, data: Record<string, unknown>): string {
  const rawConfig = data.config;
  const config =
    rawConfig && typeof rawConfig === "object" ? (rawConfig as Record<string, unknown>) : {};
  const candidates = [config.project_name, data.project, basename(workspace), "Handyman"];
  for (const candidate of candidates) {
    if (typeof candidate === "string" && candidate.length > 0) {
      return candidate;
    }
  }
  return "Handyman";
}

function featuresSection(features: Record<string, unknown>[]): string[] {
  const byStatus = new Map<string, Record<string, unknown>[]>();
  for (const feature of features) {
    const status = String(pyGet(feature, "status", "?"));
    const bucket = byStatus.get(status);
    if (bucket) {
      bucket.push(feature);
    } else {
      byStatus.set(status, [feature]);
    }
  }

  const names = (items: Record<string, unknown>[]): string => {
    const joined = items
      .map((f) => `${pyGet(f, "name", "?")} (id ${pyGet(f, "id", "?")})`)
      .join(", ");
    return joined || "_none_";
  };

  const lines = ["## Features", ""];
  for (const status of STATUS_ORDER) {
    lines.push(`- **${status}:** ${names(byStatus.get(status) ?? [])}`);
  }
  lines.push(`- **done:** ${(byStatus.get("done") ?? []).length} closed`);
  return lines;
}

/** Operator `## Notes` block from an existing index, if any. */
export function preservedNotes(indexPath: string): string[] {
  if (!isFile(indexPath)) {
    return [];
  }
  const lines = readFileSync(indexPath, "utf-8").split("\n");
  for (let i = 0; i < lines.length; i++) {
    if ((lines[i] as string).trim() === NOTES_HEADING) {
      return lines.slice(i);
    }
  }
  return [];
}

export function buildIndex(workspace: string): string {
  const listPath = join(workspace, "feature_list.json");
  let data: Record<string, unknown> = {};
  if (isFile(listPath)) {
    const parsed: unknown = JSON.parse(readFileSync(listPath, "utf-8"));
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      data = parsed as Record<string, unknown>;
    }
  }
  const rawFeatures = data.features;
  const features = Array.isArray(rawFeatures) ? (rawFeatures as Record<string, unknown>[]) : [];
  const name = projectName(workspace, data);

  // OKF reserved file: index.md carries no frontmatter.
  const out: string[] = [
    `# ${name} - Handyman Workspace`,
    "",
    "_Generated by `scripts/index_md.py` from the live workspace. Re-run to " +
      "refresh; the `## Notes` section is preserved._",
    "",
    "## State",
    "",
  ];
  // Markdown links only for files that exist (the verifier checks these resolve).
  if (isFile(listPath)) {
    out.push("- [feature_list.json](feature_list.json)");
  }
  if (isFile(join(workspace, "feature-request.md"))) {
    out.push("- [feature-request.md](feature-request.md)");
  }

  const docsDir = resolveDocsDir(workspace);
  const docsName = basename(docsDir);
  out.push("", "## Docs", "");
  for (const doc of DOCS) {
    if (isFile(join(docsDir, `${doc}.md`))) {
      out.push(`- [${doc}](${docsName}/${doc}.md)`);
    }
  }
  // Work-period docs: closed sprints and unreviewed open-sprint drafts.
  for (const path of mdNamesSorted(join(docsDir, "sprints"))) {
    out.push(`- [${stemOf(path)}](${docsName}/sprints/${path})`);
  }
  for (const path of mdNamesSorted(join(docsDir, "current"))) {
    out.push(`- [${stemOf(path)}](${docsName}/current/${path})`);
  }

  out.push("", "## Progress", "");
  for (const prog of ["current", "history"]) {
    if (isFile(join(workspace, "progress", `${prog}.md`))) {
      out.push(`- [${prog}](progress/${prog}.md)`);
    }
  }
  // Session artifacts beyond the two live files (e.g. handoffs merged from
  // the retired docs/current/ folder).
  for (const path of mdNamesSorted(join(workspace, "progress"))) {
    if (path !== "current.md" && path !== "history.md") {
      out.push(`- [${stemOf(path)}](progress/${path})`);
    }
  }

  out.push("");
  out.push(...featuresSection(features));

  out.push("", "## Backlog", "");
  const backlog = join(workspace, "backlog");
  let reports: string[];
  try {
    reports = readdirSync(backlog)
      .filter((entry) => entry.endsWith(".md"))
      .map(stemOf)
      .sort();
  } catch {
    reports = [];
  }
  if (reports.length > 0) {
    for (const stem of reports) {
      out.push(`- [${stem}](backlog/${stem}.md)`);
    }
  } else {
    out.push("- _no reports yet_");
  }

  out.push(
    "",
    "## Tags",
    "",
    "- `#handyman/feature/in_progress`",
    "- `#handyman/feature/blocked`",
    "- `#handyman/review/changes_requested`",
    "",
  );

  const notes = preservedNotes(join(workspace, "index.md"));
  if (notes.length > 0) {
    out.push(...notes);
  } else {
    out.push(NOTES_HEADING, "", "_Operator notes; preserved across regenerations._");
  }

  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

function parseRoot(argv: string[]): string {
  let root = ".";
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--root") {
      root = argv[i + 1] ?? "";
      i++;
    } else if (arg?.startsWith("--root=")) {
      root = arg.slice("--root=".length);
    }
  }
  return root;
}

export function main(argv: string[]): number {
  const rootArg = parseRoot(argv);
  // Python `Path(args.root).resolve()`: absolutize and resolve symlinks
  // (non-strict -- a missing path is still absolutized).
  let root = resolve(rootArg);
  try {
    root = realpathSync(root);
  } catch {
    // keep the absolutized path; the is-dir check below will reject it.
  }
  let rootIsDir: boolean;
  try {
    rootIsDir = statSync(root).isDirectory();
  } catch {
    rootIsDir = false;
  }
  if (!rootIsDir) {
    return err(`root is not a directory: ${root}`);
  }
  const workspace = resolveWorkspace(root);
  if (!isFile(join(workspace, "feature_list.json"))) {
    return err(`no feature_list.json under ${workspace}`);
  }
  const indexPath = join(workspace, "index.md");
  try {
    writeFileSync(indexPath, buildIndex(workspace), "utf-8");
  } catch (exc) {
    return err(exc instanceof Error ? exc.message : String(exc));
  }
  process.stdout.write(`regenerated ${indexPath}\n`);
  return 0;
}

// Run when executed directly (mirrors Python `if __name__ == "__main__"`).
if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv.slice(2)));
}
