#!/usr/bin/env bash
# =============================================================================
# lib/foreman.sh — Shared helpers for FOREMAN installer
# =============================================================================

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
foreman_info()    { echo "  [INFO]  $*"; }
foreman_success() { echo "  [OK]    $*"; }
foreman_warn()    { echo "  [WARN]  $*" >&2; }
foreman_error()   { echo "  [ERROR] $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# usage — print help text
# ---------------------------------------------------------------------------
usage() {
  cat <<'EOF'
FOREMAN — Harness-Subagents Skill Installer
============================================

Usage:
  ./install.sh [OPTIONS]

Options:
  --mode   local|global   Installation mode (default: local)
  --target <path>         Directory to install into (default: current dir)
  --help                  Show this help message

Modes:
  local   All files, including dynamic progress data, are created inside
          the target workspace directory.

          Resulting layout:
            <target>/
            ├── AGENTS.md
            ├── CHECKPOINTS.md
            └── progress/
                ├── current/
                ├── history/
                └── docs/

  global  Static config files are placed in the target workspace.
          Dynamic progress data is stored at ~/FOREMAN/<project>/.
          AGENTS.md and CHECKPOINTS.md reference that global location.

          Resulting layout:
            <target>/
            ├── AGENTS.md           ← references ~/FOREMAN/<project>/progress
            └── CHECKPOINTS.md      ← references ~/FOREMAN/<project>/progress

            ~/FOREMAN/<project>/
            └── progress/
                ├── current/
                ├── history/
                └── docs/

Examples:
  # Install locally in the current directory
  ./install.sh --mode local

  # Install globally, pointing to ~/FOREMAN/my-project/
  ./install.sh --mode global

  # Install locally into a specific directory
  ./install.sh --mode local --target /path/to/project

EOF
}

# ---------------------------------------------------------------------------
# install_progress_structure <progress_dir>
#
#   Creates the standard harness-subagents progress directory layout:
#     <progress_dir>/
#     ├── current/     — active work state
#     ├── history/     — completed task records
#     └── docs/        — generated documentation
# ---------------------------------------------------------------------------
install_progress_structure() {
  local progress_dir="$1"

  foreman_info "Creating progress directory structure..."

  mkdir -p "$progress_dir/current"
  mkdir -p "$progress_dir/history"
  mkdir -p "$progress_dir/docs"

  # Seed placeholder files so directories are tracked by VCS
  _write_if_absent "$progress_dir/current/.gitkeep"   ""
  _write_if_absent "$progress_dir/history/.gitkeep"   ""
  _write_if_absent "$progress_dir/docs/.gitkeep"      ""

  # Create default current-state file
  _write_if_absent "$progress_dir/current/state.md" "$(cat <<'STATE'
# Current State

<!-- This file is managed by FOREMAN. Update it to track the active task. -->

## Active Task
_No active task._

## Context
_No context recorded._

## Next Steps
_No next steps defined._
STATE
)"

  # Create default history index
  _write_if_absent "$progress_dir/history/index.md" "$(cat <<'HISTORY'
# History Index

<!-- FOREMAN appends entries here as tasks are completed. -->

| Date | Task | Status |
|------|------|--------|
HISTORY
)"

  foreman_success "Progress structure created at: $progress_dir"
}

# ---------------------------------------------------------------------------
# install_agents_md <target_dir> <mode> <project_name> <progress_path>
#
#   Generates AGENTS.md inside <target_dir>.
#   <progress_path> is the path written into the file — relative for local,
#   absolute for global.
# ---------------------------------------------------------------------------
install_agents_md() {
  local target_dir="$1"
  local mode="$2"
  local project_name="$3"
  local progress_path="$4"
  local dest="$target_dir/AGENTS.md"

  foreman_info "Generating AGENTS.md..."

  if [[ -f "$dest" ]]; then
    foreman_warn "AGENTS.md already exists — skipping (delete it first to regenerate)."
    return 0
  fi

  cat > "$dest" <<AGENTS_MD
# AGENTS.md — Harness-Subagents Configuration
<!-- Generated by FOREMAN installer | mode: ${mode} | project: ${project_name} -->

## Overview
This file configures the harness-subagents framework for the **${project_name}** project.
All agent operations that read or write dynamic state must use the paths defined here.

## Installation Mode
\`\`\`
mode: ${mode}
\`\`\`

$(if [[ "$mode" == "global" ]]; then
cat <<GLOBAL_NOTE
> **Global mode** — Dynamic progress data is stored outside this repository in a
> shared FOREMAN workspace. Do **not** hardcode local \`./progress/\` paths in agent
> instructions; always use the \`PROGRESS_DIR\` variable below.

GLOBAL_NOTE
fi)

## Paths
| Variable         | Value |
|-----------------|-------|
| \`PROGRESS_DIR\` | \`${progress_path}\` |
| \`CURRENT_DIR\`  | \`${progress_path}/current\` |
| \`HISTORY_DIR\`  | \`${progress_path}/history\` |
| \`DOCS_DIR\`     | \`${progress_path}/docs\` |

## Agent Instructions

### Reading Current State
Agents should read the active task context from:
\`\`\`
${progress_path}/current/state.md
\`\`\`

### Persisting Progress
- Write incremental notes to \`${progress_path}/current/state.md\`.
- Upon task completion, move a summary to \`${progress_path}/history/\` and
  append an entry to \`${progress_path}/history/index.md\`.

### Generating Documentation
- Place generated docs under \`${progress_path}/docs/\`.

## Conventions
1. Never commit the \`progress/\` directory if it lives inside the repository
   (local mode). Add it to \`.gitignore\`.
2. In global mode the \`progress/\` directory lives at \`${progress_path}\`
   and is shared across all checkouts of this project.
3. Each agent session should start by reading \`${progress_path}/current/state.md\`
   and end by updating it.
AGENTS_MD

  foreman_success "AGENTS.md written to: $dest"
}

# ---------------------------------------------------------------------------
# install_checkpoints_md <target_dir> <mode> <project_name> <progress_path>
#
#   Generates CHECKPOINTS.md inside <target_dir>.
# ---------------------------------------------------------------------------
install_checkpoints_md() {
  local target_dir="$1"
  local mode="$2"
  local project_name="$3"
  local progress_path="$4"
  local dest="$target_dir/CHECKPOINTS.md"

  foreman_info "Generating CHECKPOINTS.md..."

  if [[ -f "$dest" ]]; then
    foreman_warn "CHECKPOINTS.md already exists — skipping (delete it first to regenerate)."
    return 0
  fi

  cat > "$dest" <<CHECKPOINTS_MD
# CHECKPOINTS.md — Task Checkpoint Tracker
<!-- Generated by FOREMAN installer | mode: ${mode} | project: ${project_name} -->

## Overview
This file tracks milestones and checkpoints for the **${project_name}** project.
Detailed work history is stored in:

\`\`\`
${progress_path}/history/
\`\`\`

$(if [[ "$mode" == "global" ]]; then
cat <<GLOBAL_NOTE
> **Global mode** — The history and docs directories referenced above reside
> outside this repository at \`${progress_path}\`. Update this file and those
> directories consistently.

GLOBAL_NOTE
fi)

## Storage Locations
| Content               | Location |
|-----------------------|----------|
| Checkpoint entries    | This file (\`CHECKPOINTS.md\`) |
| Detailed task history | \`${progress_path}/history/index.md\` |
| Supporting docs       | \`${progress_path}/docs/\` |
| Active task state     | \`${progress_path}/current/state.md\` |

## Active Checkpoint
_No active checkpoint. Run \`./install.sh\` and start your first task._

## Checkpoint Log

<!-- Append entries below using the template:

### [YYYY-MM-DD] <Title>
- **Status**: in-progress | completed | blocked
- **Description**: Brief description of what was done.
- **History file**: ${progress_path}/history/<filename>.md

-->

CHECKPOINTS_MD

  foreman_success "CHECKPOINTS.md written to: $dest"
}

# ---------------------------------------------------------------------------
# _write_if_absent <path> <content>
#
#   Creates <path> with <content> only when the file does not yet exist.
# ---------------------------------------------------------------------------
_write_if_absent() {
  local path="$1"
  local content="$2"

  if [[ ! -f "$path" ]]; then
    printf '%s' "$content" > "$path"
  fi
}
