#!/usr/bin/env python3
"""Regenerate the Handyman index.md (Obsidian MOC) from live workspace state.

The Map Of Content hub should list what actually exists in HARNESS_WORKSPACE --
the feature backlog grouped by status, the docs, the progress files, and the
backlog reports -- so it stays accurate without hand-editing. A `## Notes`
section is preserved across regenerations for operator-authored content.

Only files that exist are linked. Vault-internal targets use wikilinks
(`[[...]]`); `feature_list.json` and `feature-request.md` use markdown links so
they resolve in plain readers too.

Usage:
    python scripts/index_md.py [--root PATH]

Exit codes: 0 ok, 1 error.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# scripts/ is on sys.path[0] when run as a script, so this resolves.
from validate_harness import resolve_workspace

DOCS = ("business", "architecture", "conventions", "verification")
STATUS_ORDER = ("in_progress", "pending", "blocked")
NOTES_HEADING = "## Notes"


def err(msg: str) -> int:
    print(f"error: {msg}", file=sys.stderr)
    return 1


def _project_name(workspace: Path, data: dict) -> str:
    config = data.get("config") or {}
    return (
        config.get("project_name")
        or data.get("project")
        or workspace.name
        or "Handyman"
    )


def _features_section(features: list) -> list[str]:
    by_status: dict[str, list] = {}
    for feature in features:
        by_status.setdefault(feature.get("status", "?"), []).append(feature)

    def names(items: list) -> str:
        return ", ".join(
            f"{f.get('name', '?')} (id {f.get('id', '?')})" for f in items
        ) or "_none_"

    lines = ["## Features", ""]
    for status in STATUS_ORDER:
        lines.append(f"- **{status}:** {names(by_status.get(status, []))}")
    lines.append(f"- **done:** {len(by_status.get('done', []))} closed")
    return lines


def _preserved_notes(index_path: Path) -> list[str]:
    """Return the operator `## Notes` block from an existing index, if any."""
    if not index_path.is_file():
        return []
    lines = index_path.read_text(encoding="utf-8").split("\n")
    for i, line in enumerate(lines):
        if line.strip() == NOTES_HEADING:
            return [l.rstrip("\n") for l in lines[i:]]
    return []


def build_index(workspace: Path) -> str:
    list_path = workspace / "feature_list.json"
    data = json.loads(list_path.read_text(encoding="utf-8")) if list_path.is_file() else {}
    if not isinstance(data, dict):
        data = {}
    features = data.get("features", [])
    name = _project_name(workspace, data)

    out: list[str] = [
        "---",
        "tags: [handyman/moc]",
        "---",
        "",
        f"# {name} - Handyman Workspace",
        "",
        "_Generated by `scripts/index_md.py` from the live workspace. Re-run to "
        "refresh; the `## Notes` section is preserved._",
        "",
        "## State",
        "",
    ]
    # Markdown links only for files that exist (the verifier checks these resolve).
    if list_path.is_file():
        out.append("- [feature_list.json](feature_list.json)")
    if (workspace / "feature-request.md").is_file():
        out.append("- [feature-request.md](feature-request.md)")

    out += ["", "## Docs", ""]
    for doc in DOCS:
        if (workspace / "docs" / f"{doc}.md").is_file():
            out.append(f"- [[docs/{doc}]]")

    out += ["", "## Progress", ""]
    for prog in ("current", "history"):
        if (workspace / "progress" / f"{prog}.md").is_file():
            out.append(f"- [[progress/{prog}]]")

    out += [""] + _features_section(features)

    out += ["", "## Backlog", ""]
    backlog = workspace / "backlog"
    reports = sorted(p.stem for p in backlog.glob("*.md")) if backlog.is_dir() else []
    if reports:
        out += [f"- [[backlog/{stem}]]" for stem in reports]
    else:
        out.append("- _no reports yet_")

    out += [
        "",
        "## Tags",
        "",
        "- `#handyman/feature/in_progress`",
        "- `#handyman/feature/blocked`",
        "- `#handyman/review/changes_requested`",
        "",
    ]

    notes = _preserved_notes(workspace / "index.md")
    if notes:
        out += notes
    else:
        out += [NOTES_HEADING, "",
                "_Operator notes; preserved across regenerations._"]

    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Project root (default: cwd).")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    if not root.is_dir():
        return err(f"root is not a directory: {root}")
    workspace = resolve_workspace(root)
    if not (workspace / "feature_list.json").is_file():
        return err(f"no feature_list.json under {workspace}")
    index_path = workspace / "index.md"
    try:
        index_path.write_text(build_index(workspace), encoding="utf-8")
    except (ValueError, OSError) as exc:
        return err(str(exc))
    print(f"regenerated {index_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
