import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { loadFeatureList, saveFeatureList, serializeFeatureList } from "./featureList.js";

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "hm-fl-"));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe("serializeFeatureList", () => {
  it("matches Python json.dumps(indent=2, ensure_ascii=False) + newline", () => {
    const data = { project: "p", features: [{ id: 1, name: "café 🚀" }] };
    // Byte-for-byte reference generated by:
    //   python3 -c "import json;print(json.dumps(obj, indent=2, ensure_ascii=False))"
    const expected =
      "{\n" +
      '  "project": "p",\n' +
      '  "features": [\n' +
      "    {\n" +
      '      "id": 1,\n' +
      '      "name": "café 🚀"\n' +
      "    }\n" +
      "  ]\n" +
      "}\n";
    expect(serializeFeatureList(data)).toBe(expected);
  });

  it("leaves non-ASCII unescaped (no \\uXXXX)", () => {
    const s = serializeFeatureList({ name: "café ñ 日本 🚀" });
    expect(s).toContain("café ñ 日本 🚀");
    expect(s).not.toContain("\\u");
  });
});

describe("saveFeatureList / loadFeatureList", () => {
  it("round-trips and writes exactly serializeFeatureList bytes (UTF-8, no BOM)", () => {
    const data = { project: "p", config: { harness_workspace: "café" }, features: [] };
    const path = join(dir, "feature_list.json");
    saveFeatureList(path, data);

    const bytes = readFileSync(path);
    expect(bytes[0]).not.toBe(0xef); // no UTF-8 BOM
    expect(bytes.toString("utf-8")).toBe(serializeFeatureList(data));
    expect(loadFeatureList(path)).toEqual(data);
  });

  it("overwrites atomically without leaving temp files behind", () => {
    const path = join(dir, "feature_list.json");
    saveFeatureList(path, { v: 1 });
    saveFeatureList(path, { v: 2 });
    expect(loadFeatureList(path)).toEqual({ v: 2 });
    const leftovers = readFileSync;
    expect(() => leftovers(path)).not.toThrow();
  });
});
